name: project_fitcru
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  cloud_firestore: ^4.14.0
  cloud_firestore_odm: ^1.0.0-dev.82

  collection: ^1.17.2
  dio: ^5.4.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  fl_chart: ^0.40.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.8.1
  uuid: ^4.2.2
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  cloud_firestore_odm_generator: ^1.0.0-dev.73
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0
flutter:
  uses-material-design: true

  assets:
    - assets/loginBackground.gif
    - assets/food_guide_tables/

  fonts:
    - family: YesevaOne
      fonts:
        - asset: assets/fonts/Yeseva_One/YesevaOne-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 300
